article/urls.py
# 引入path
from django.urls import path,include
from article import views
# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    # path函数将url映射到视图
    path('',views.article_list, name='article_list'),
    # path('list/', views.article_list, name='article_list'),
    path('details/<int:article_id>', views.article_details, name='article_details'),
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 发表评论
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
    path('getqq',views.get_qq_msg,name='getqq'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from comment import views

urlpatterns = [
    path('',include('article.urls', namespace='index')),
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('comment/', include('comment.urls', namespace='comment')),
    # path函数将url映射到视图
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
# timezone 用于处理时间相关事务。
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.


class ArticleColumn(models.Model):
    title = models.CharField(max_length=50, blank=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class ArticlePost(models.Model):
    # 文章作者。参数 on_delete 用于指定数据删除的方式
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # 文章标题。models.CharField 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)
    # 文章栏目
    column = models.ForeignKey(ArticleColumn,null=True,blank=True,on_delete=models.CASCADE,related_name='article')
    # 标签
    tags = TaggableManager(blank=True)
    # 简介
    profile = models.TextField(default=0)
    # 文章正文。保存大量文本使用 TextField
    body = models.TextField()
    # 文章创建时间。参数 default=timezone.now 指定其在创建数据时将默认写入当前的时间
    created = models.DateTimeField(default=timezone.now)
    # 文章更新时间。参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)
    # 文章浏览量
    totalviews = models.PositiveIntegerField(default=0)

    # 获取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-created' 表明数据应该以倒序排列
        ordering = ('-created',)

    # 函数 __str__ 定义当调用对象的 str() 方法时的返回值内容
    def __str__(self):
        # return self.title 将文章标题返回
        return self.title


comment/models.py
from django.db import models
from article.models import ArticlePost
from ckeditor.fields import RichTextField
# Create your models here.
class Comment(models.Model):
    article = models.ForeignKey(ArticlePost,on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80,default='tfl',null=True)
    body = RichTextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ('created',)

    def __str__(self):
        return self.body[:20]

article/forms.py
from django import forms
from .models import ArticlePost

class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title','body')

comment/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','body']

article/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from comment.models import Comment
from comment.forms import CommentForm
# 导入 HttpResponse 模块
from django.http import HttpResponse
# 导入数据模型ArticlePost
from .models import ArticlePost
from .models import ArticleColumn
import markdown


def article_list(request):
    # 取出所有博客文章
    articles = ArticlePost.objects.all()
    columns = ArticleColumn.objects.all()
    articles_1 = articles
    for article in articles:
        article.body = markdown.markdown(article.body, extensions=[
            # 包含 缩写、表格等常用扩展
            'markdown.extensions.extra',
            # 语法高亮扩展
            'markdown.extensions.codehilite',
        ])
    # 需要传递给模板（templates）的对象
    paginator = Paginator(articles, 5)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    column_num = {}
    # 计算每一个栏目里文章数量--初始化init
    for ct in columns:
        column_num[ct.title] = 0
    flag = True
    for at in articles_1:
        # 求有多少不同的标签沃日
        if flag==True:
            flag = False
            tag_list = at.tags.all()
        qa = at.tags.all()
        tag_list = tag_list | qa
        # 计算每一个栏目里文章数量
        if at.column.title in column_num:
            column_num[at.column.title] += 1

    # 去重
    tag_list = tag_list.distinct()
    context = {'articles': articles, 'columns': columns, 'column_num': column_num, 'tag_list': tag_list}
    # render函数：载入模板，并返回context对象
    return render(request, 'article/blog.html', context)




# 视图函数
def article_details(request, article_id):
    comment_form = CommentForm()
    article = ArticlePost.objects.get(pk=article_id)
    comments = Comment.objects.filter(article=article_id)
    article.totalviews += 1
    article.save(update_fields = ['totalviews'])
    md = markdown.Markdown(extensions=[
        # 包含 缩写、表格等常用扩展
        'markdown.extensions.extra',
        # 语法高亮扩展
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
        ])
    article.body = md.convert(article.body);
    context = {'article': article,
               'toc':md.toc,
               'comments': comments,
               'comment_form': comment_form,}
    return render(request, 'article/details.html', context)
# Create your views here.

comment/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from article.models import ArticlePost
from .forms import CommentForm
import http.client
import urllib
# 文章评论
def post_comment(request,article_id):
    article = get_object_or_404(ArticlePost, id=article_id)
    comments = article.comments.filter(active=True)
    # 处理 POST 请求
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.article = article
            # new_comment.user = request.user
            new_comment.save()
            return redirect("/article/details/"+str(article_id))
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 处理错误请求
    else:
        return HttpResponse("发表评论仅接受POST请求。")

# 通过qq号获取name
def get_qq_msg(request):
    # 1. 建立HTTP连接
    res = urllib.request.urlopen("https://api.toubiec.cn/qq?qq=2320456951&size=100")
    # print(res.read().decode("utf-8"))  # 自己解码
    return HttpResponse(res.read().decode("utf-8"))

templates/article/blog.html
<!-- extends表明此页面继承自 base.html 文件 -->

{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
<div class="zhong1 bc_1">
				<!--中1  - 轮播-->
				<div class="lb">
					
				</div>
				
				<!--中1  -  个人-->
				<div class="person">
					
				</div>
				
				<!--中1  -  标签-->
				<div class="tags">
				
				</div>
			</div>
			
			
			<div class="spa" style="text-align: center; height: 100px; ">
				<div style=" padding-top: 25px;">
					<img src="{%static 'img/书.svg' %} " width="50px" >
				</div>
					
			</div>
			
		<div class="mid">
			<!--中1-->
			
			<div class="container mid-left bc_6">
				<div class="blog-classify-name">
					<div class="Categories">
						<img src="{%static 'img/太阳.svg' %} " width="23px" style="padding-bottom: 6px;">
						<span>博客分类</span>
					</div>
					<div class="blog-classify-body">
						
						{% for column in columns %}
									<a href="">
										<div class="categories-set">
											<div class="categories-set-box">
												<div class="categories-set-left">
												</div>
												<div class="categories-set-mid">
													<span>{{ column.title }}</span>
												</div>
												<div class="categories-set-right">
													{% for key,val in column_num.items %}
														{% if column.title == key %}
															<span>({{ val }})</span>
														{% endif %}
													{% endfor %}
												</div>
											</div>
										</div>
									</a>
						{% endfor %}
					</div>
					<br>
					<hr >
				</div>
				
				
				<div class="blog-classify-name">
					<div class="Categories">
						<img src="{%static 'img/笑脸.svg' %} " width="23px" style="padding-bottom: 6px;">
						<span>关于博主</span>
					</div>
					
					<div class="blog-classify-body">
						<div class="tx">
							<img src="{%static 'img/hs.jpg' %}" width="60px">
							<span>让我们红橙作伴活的潇潇洒洒</span>
						</div>
						
					</div>
					<br>
					<hr >
				</div>
				
				<div class="blog-classify-name">
					<div class="Categories">
						<img src="{%static 'img/花.svg' %} " width="23px" style="padding-bottom: 6px;">
						<span>标签</span>
					</div>
					
					<div class="blog-classify-body">
						<div class="tags-set">
							{% for val in tag_list %}
										<a href="">
											<div class="tag-set">
												<span>{{ val }}</span>
											</div>
										</a>
							{% endfor %}
							
						</div>
					</div>
					<br>
					<hr >
				</div>
				
			</div>
			<!--中2-文章1-n-->
				<div class="container mid-right">
				    <div class="row mt-2">
				
				        {% for article in articles %}
				        <!-- 文章内容 -->
			
							<article class="article">
								<div id="title">
									<h4 style="color: #555555;"><strong><a href="{% url 'article:article_details' article.id %}" class="un">{{ article.title }}</a></strong></h4>
								</div>
								<div id="data"><strong>
								<img src="{%static 'img/钟.svg' %}" width="15px" height="15px"><span> {{ article.created }}</span> | 
								<span><img src="{%static 'img/文档.svg' %}" width="15px" height="15px"> {{article.column}}</span> |
								<span><img src="{%static 'img/眼睛.svg' %}" width="15px" height="15px"> {{article.totalviews}}</span>
								</strong>
									
								</div>
								
								<div id="content">
									<a href="{% url 'article:article_details' article.id %}" class="un"><p>{{ article.profile|safe }}</p></a>
								</div>
								
								<div id="more">
									<a href="{% url 'article:article_details' article.id %}" class="btn btn-primary btn-secondary">READ MORE</a>
								</div>
								<div class="bk">
									<div class="bk-dh">
										
									</div>
								</div>
							</article>
					
							
				        
						{% endfor %}
				
				    </div>
				</div>
			</div>
		</div>
		<!--翻页-->
		<div class="nextpage">
			<div class="m-auto">
				{% if articles.has_previous %}
				<a href="?page=1" class="btn btn-success">&laquo; 1</a><span> ... </span>
				<a href="?page={{ articles.previous_page_number }}" class="btn btn-secondary">{{ articles.previous_page_number }}</a>
				{% endif %}&nbsp;&nbsp;
				<span class="btn btn-danger btn-lg">{{articles.number}}</span>
				&nbsp;&nbsp;
				{% if articles.has_next %}
					<a href="?page={{articles.next_page_number}}" class="btn btn-secondary">{{articles.next_page_number}}</a><span> ... </span>
					<a href="?page={{articles.next_page_number}}" class="btn btn-success">{{ articles.paginator.num_pages }} &raquo;</a>
				{% endif %}
			</div>
			
		</div>
<!-- 定义放置文章标题的div容器 -->

{% endblock content %}

templates/article/details.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div style="height: 20px;">
</div>
<div id="dts">
<article class="article-details">
	<div id="title" >
		<h2 style="color: #555555;"><strong>{{ article.title }}</strong></h2>
	</div> 
	<div id="data"><strong>
	<img src="{%static 'img/钟.svg' %}" width="15px" height="15px"><span> {{ article.created }}</span> | 
	<span><img src="{%static 'img/文档.svg' %}" width="15px" height="15px"> {{article.column}}</span> |
	<span><img src="{%static 'img/眼睛.svg' %}" width="15px" height="15px"> {{article.totalviews}}</span>
	</strong>
		
	</div>
	
	<div id="content">
		<p>{{ article.body|safe }}</p>
	</div>
	
	<div id="more">
		<a href="{% url 'article:article_details' article.id %}" class="btn btn-primary btn-secondary">READ MORE</a>
	</div>

</article>


<div class="col-3 mt-4">
            <h4><strong>目录</strong></h4>
            <hr>
            <div>
                {{ toc|safe }}
            </div>
        </div>
<div class="col-9">
    <!-- 已有代码，文章正文 -->
    <div class="col-12">
    </div>

    <!-- 发表评论 -->
    <hr>
        <div>
            <form 
                action="{% url 'comment:post_comment' article.id %}" 
                method="POST"
            >
            {% csrf_token %}
                <div class="form-group">
                    <label for="body">
                        <strong>
                            我要发言：
                        </strong>
                    </label>
					<br>
					<strong>
					    姓名:
					</strong>
					<textarea
					    type="text" 
					    class="form-control" 
					    id="nameeee" 
					    name="name" 
					    rows="1"
						></textarea>
						<strong>
						    留言:
						</strong>
                    <div>
                        {{ comment_form.media }}
                        {{ comment_form.body }}
                    </div>
					
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary ">发送</button>                    
            </form>
        </div>
        <br>




    <!-- 显示评论 -->
    <h4>共有{{ comments.count }}条评论</h4>
    <div>
        {% for comment in comments %}
            <hr>
            <p>
                <strong style="color: pink">
                    {{ comment.name }}
                </strong> 于 
                <span style="color: green">
                    {{ comment.created|date:"Y-m-d H:i:s" }}
                </span> 时说：
            </p>
            <pre style="font-family: inherit; font-size: 1em;">
					{{ comment.body|safe }}</pre>
        {% endfor %}
    </div>
</div>
</div>
	{% block script %}
	<script>
	    $(".django-ckeditor-widget").removeAttr('style');
	</script>
	{% endblock script %}
{% endblock content %}

templates/base.html
<!-- 载入静态文件 -->
{% load static %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
	
      <link rel="stylesheet" href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdn.bootcss.com/popper.js/1.15.0/esm/popper.min.js"></script>
        <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
	  <link rel="stylesheet" href="{% static 'css/monokai.css' %}">
	  
	  <link rel="stylesheet" href="{%static 'css/index.css' %}">
	  <link rel="stylesheet" href="{%static 'css/bg_color.css' %}">
	  <link rel="stylesheet" href="{%static 'css/midone.css' %}">
	  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	 
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}
	
	{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
	<!--返回顶部-->
	<div id="toTop">
		<img src="{%static 'img/totop.svg' %}" class="top">
	</div>
	
	<!--<script src="https://kit.fontawesome.com/693487bce5.js" crossorigin="anonymous"></script>-->
    <script src="{%static 'js/index.js' %}"></script>
	{% block script %}{% endblock script %}
</body>

</html>

templates/footer.html
{% load static %}
<!-- Footer -->

<footer class="bg-dark" style="margin-top: 100px;height: 60px;">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; TFLye 2020</p>
    </div>
</footer>

templates/header.html
{% load static %}
<!--导航-->
<div class="">
	<div class="">
	</div>
	<nav class="nv2 navbar navbar-expand-md navbar-dark  bc_5 nav" id="" >
	  <!-- Brand/logo -->
	  
	  <!-- Links -->
	   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	 <div class="nav justify-content-center collapse navbar-collapse" id="collapsibleNavbar">
		 <img src="{%static 'img/帽子.svg' %}" width="30px" style="float: right;right:top: 20px;">
	  <ul class="navbar-nav " >
	    <li class="nav-item">
	      <a class="nav-link" href="{% url 'index:article_list' %}">首页</a>
	    </li>
	    <li class="nav-item">
	      <a class="nav-link" href="#">归档</a>
	    </li>
	    <li class="nav-item">
	      <a class="nav-link" href="#">留言</a>
	    </li>
		<li class="nav-item ">
		  <a class="navbar-brand" href="#"> 时夜</a>
		</li>
		
		<li class="nav-item">
		  <a class="nav-link" href="#">分享</a>
		</li>
		
		<li class="nav-item">
		  <a class="nav-link" href="#">阿友</a>
		</li>
		<li class="nav-item">
		  <a class="nav-link" href="#">关于</a>
		</li>
	  </ul>
	  </div>
	</nav>
	
	<div class="nv3">
		
	</div>
	
</div>
		